services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: obsidian-tebla-plugin-dev
    volumes:
      - .:/opt/nodeApp/app
    environment:
      PATH: /opt/nodeApp/app/node_modules/.bin:$PATH
    command: sh -c "[ -d /opt/nodeApp/node_modules ] && rm -rf
      /opt/nodeApp/app/node_modules && mv /opt/nodeApp/node_modules
      /opt/nodeApp/app; node esbuild.config.mjs"
